name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_base:
    git:
      url: https://gitee.com/luoyi666/flutter_base.git
  decimal: ^3.0.0
  custom_pop_up_menu: ^1.2.4
  flutter_syntax_view: ^4.1.0
  translator: ^1.0.0

dev_dependencies:
  flutter_lints: ^4.0.0

dependency_overrides:
  flutter_element_ui:
    path: ../
  web: ^1.0.0

flutter:
  uses-material-design: true
#  fonts:
#    - family: NotoSansSC
#      fonts:
#        - asset: assets/fonts/NotoSansSC-Bold.ttf
#        - asset: assets/fonts/NotoSansSC-Medium.ttf
