name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_base:
    path: ../packages/flutter_base
  decimal: ^3.0.0
  defer_pointer: ^0.0.2
  custom_pop_up_menu: ^1.2.4
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
#  fonts:
#    - family: NotoSansSC
#      fonts:
#        - asset: packages/luoyi_flutter_font/fonts/NotoSansSC/700.ttf
#        - asset: packages/luoyi_flutter_font/fonts/NotoSansSC/500.ttf
