name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_element_ui:
    path: ..
  flutter_base:
    git:
      url: https://gitee.com/luoyi666/flutter_base.git
      ref: v0.0.8
  flutter_plugin:
    git:
      url: https://gitee.com/luoyi666/flutter_plugin.git
      ref: v0.0.5
  cupertino_icons: ^1.0.2
  chicago: ^0.4.2-dev
  ionicons: ^0.2.2
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.1
  logger: ^2.1.0
  morphable_shape: ^1.6.6
  non_uniform_border: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

