name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_element_ui:
    path: ../packages/flutter_element_ui
  flutter_element_annotation:
    path: ../packages/flutter_element_annotation
  go_router: ^14.0.1
  faker: ^2.1.0
  super_sliver_list: ^0.4.1
  flutter_hooks: ^0.20.5
  gap: ^3.0.1
  decimal: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  flutter_element_generator:
    path: ../packages/flutter_element_generator

dependency_overrides:
  luoyi_flutter_base:
    git:
      url: https://github.com/luoyi58624/luoyi_flutter_base

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Bold.ttf
        - asset: assets/fonts/NotoSansSC-Medium.ttf
        - asset: assets/fonts/NotoSansSC-Regular.ttf
