name: element_extension
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  element_plus:
    path: ../element_plus
  element_dart:
    path: ../element_dart
  element_annotation:
    path: ../element_annotation
  flutter_obs:
    path: ../flutter_obs
  archive: ^3.4.10
  crypto: ^3.0.3
  logger: ^2.4.0
  uuid: ^4.4.2
  collection: ^1.18.0
  gap: ^3.0.1
  flutter_hooks: ^0.20.5
  super_sliver_list: ^0.4.1
  web: ^1.0.0
  meta: ^1.12.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_lints: ^4.0.0
