targets:
  $default:
    auto_apply_builders: true
    # 指定 build_runner 全局工作目录
    sources:
      - lib/**
      - $package$
    builders:
      # 配置源码生成，将源文件与生成的代码进行关联映射，统一将生成的代码放到 generates 文件目录下
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/src/{{}}.dart': 'lib/src/generates/{{}}.g.dart'
      # 添加 element 生成器，指定检索目录，尽量将检索范围控制在需要生成的代码目录，这样可以极大提高构建速度
      flutter_element_generator|model:
        generate_for:
          - lib/src/components/**.dart
          - lib/src/themes/**.dart