targets:
  $default:
    auto_apply_builders: true
    # 指定 build_runner 检索的代码目录
    sources:
      - lib/**
      - $package$
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            # 源文件与生成的代码进行关联映射，统一将所有目标代码生成到 generates 文件目录下
            '^lib/src/{{}}.dart': 'lib/src/generates/{{}}.g.dart'
      # 配置 Element UI 代码生成器，指定需要生成的目录
      flutter_element_generator|model:
        generate_for:
          - lib/src/components/**.dart
          - lib/src/themes/**.dart