name: flutter_element_ui
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  luoyi_flutter_base: ^2.3.0
  flutter_element_annotation:
    path: ./packages/flutter_element_annotation
  flutter_svg: ^2.0.10+1
  super_sliver_list: ^0.4.1
  defer_pointer: ^0.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  flutter_element_generator:
    path: ./packages/flutter_element_generator

flutter:
  assets:
    - assets/icons/

