name: flutter_element_ui
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_element_annotation:
    path: ./packages/flutter_element_annotation
  luoyi_dart_base: ^1.11.0
  gap: ^3.0.1
  flutter_hooks: ^0.20.5
  flutter_obs: ^1.2.2
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.4
  super_sliver_list: ^0.4.1
  defer_pointer: ^0.0.2
  url_launcher: ^6.3.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  localstorage: ^5.0.0
  flutter_animate: ^4.5.0
  tinycolor2: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  flutter_element_generator:
    path: ./packages/flutter_element_generator

flutter:
  assets:
    - assets/icons/

