name: flutter_base
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  element_plus:
    path: ../element_plus
  element_dart:
    path: ../element_dart
  element_flutter:
    path: ../element_flutter
  element_annotation:
    path: ../element_annotation
  flutter_obs:
    path: ../flutter_obs
  collection: ^1.18.0
  dio: ^5.4.2
  dio_smart_retry: ^6.0.0
  go_router: ^14.1.4
  faker: ^2.1.0
  device_info_plus: ^10.1.0
  super_sliver_list: ^0.4.1
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  http: ^1.2.2
  translator: ^1.0.3+1
  syntax_highlight: ^0.4.0
  get: ^5.0.0-release-candidate-9.2.1

dev_dependencies:
  flutter_lints: ^4.0.0

