name: flutter_base
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  luoyi_flutter_base:
    git:
      url: https://github.com/luoyi58624/luoyi_flutter_base.git
  flutter_element_ui:
    git:
      url: https://github.com/luoyi58624/flutter_element_ui.git
  luoyi_flutter_font: ^1.1.0
  dio: ^5.4.2
  dio_smart_retry: ^6.0.0
  get: ^5.0.0-release-candidate-6
  go_router: ^14.1.4
  faker: ^2.1.0
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

