name: flutter_base
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_element_ui:
    path: ../..
  flutter_obs: ^1.2.2
  luoyi_dart_base: ^1.11.0
  luoyi_flutter_font: ^1.1.0
  dio: ^5.4.2
  dio_smart_retry: ^6.0.0
  get: ^5.0.0-release-candidate-6
  go_router: ^14.1.4
  faker: ^2.1.0
  url_launcher: ^6.3.0
  gap: ^3.0.1
  flutter_hooks: ^0.20.5
  super_sliver_list: ^0.4.1
  device_info_plus: ^10.1.0
  localstorage: ^5.0.0
  collection: ^1.18.0
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

