name: flutter_element_extension
description: "flutter_element_ui extension package, I don't advise you to rely on it, If there are apis you need, copy them directly."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_element_ui:
    path: ../../
  flutter_obs: ^1.6.3
  logger: ^2.4.0
  uuid: ^4.4.2
  syntax_highlight: ^0.4.0
  collection: ^1.18.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/code_themes/
