name: flutter_element_annotation
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter_element_dart:
    path: ../flutter_element_dart
  meta: ^1.12.0
