targets:
  $default:
    auto_apply_builders: true
    # 指定 build_runner 工作目录
    sources:
      - lib/**
      - $package$
    builders:
      # 配置源码生成位置，统一将生成的代码放到 generates 文件目录下
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/src/{{}}.dart': 'lib/src/generates/{{}}.g.dart'
      # 指定 element model 实体类生成器，注意：如果名字配置错了 build_runner 将使用默认配置
      element_generator|model:
        generate_for:
          - lib/src/app/index.dart
          - lib/src/components/**.dart
        options:
          # 配置生成的默认模型对象名字，默认：$${{}}
          model_name_template: '_{{}}'
      element_generator|themeModel:
        generate_for:
          - lib/src/app/index.dart
          - lib/src/components/**.dart
      element_generator|globalThemeModel:
        generate_for:
          - lib/src/app/index.dart