targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/src/styles/{{}}.dart': 'lib/src/generates/styles/{{}}.g.dart'
      flutter_element_generator|model:
        generate_for:
          include:
            - lib/src/styles/**.dart