name: element_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  # 编码和解码各种存档和压缩格式
  archive: ^3.4.10
  # 一组加密哈希函数：MD5、SHA
  crypto: ^3.0.3
  logger: ^2.4.0
  path: ^1.9.0
  uuid: ^4.4.2
  collection: ^1.18.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
