name: element_storage
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  element_flutter:
    path: ../element_flutter
  web: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_lints: ^4.0.0
