builders:
  model:
    import: "package:element_generator/builder.dart"
    builder_factories: [ "elBuilder" ]
    build_extensions: { ".dart": [ ".g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen:combining_builder" ]