name: element_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  element_dart:
    path: ../element_dart
  element_annotation:
    path: ../element_annotation
  analyzer: ^6.4.1
  meta: ^1.12.0
  build: ^2.4.1
  source_gen: ^1.5.0
  source_helper: ^1.3.4
  path: ^1.9.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.4.10
