name: element_test
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_obs:
    path: ../flutter_obs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

