import 'package:example/global.dart';
import 'package:flutter/widgets.dart';

class Button2Page extends HookWidget {
  const Button2Page({super.key});

  @override
  Widget build(BuildContext context) {
    final (count, addCount) = useCount();
    final (disabled, toggleDisabled) = useToggle();
    return SingleChildScrollView(
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Gap(8),
            ElButton2(disabled ? 'Enabled' : 'Disabled', onClick: toggleDisabled),
            ElButton2('你好'),
            const Gap(12),
            Text('普通按钮', style: context.h3),
            const Gap(8),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                ElButton2('Default: $count', disabled: disabled, onClick: addCount),
                ElButton2('Primary: $count', type: ElThemeType.primary, disabled: disabled, onClick: addCount),
                ElButton2('Success: $count', type: ElThemeType.success, disabled: disabled, onClick: addCount),
                ElButton2('Info: $count', type: ElThemeType.info, disabled: disabled, onClick: addCount),
                ElButton2('Warning: $count', type: ElThemeType.warning, disabled: disabled, onClick: addCount),
                ElButton2('Error: $count', type: ElThemeType.error, disabled: disabled, onClick: addCount),
              ],
            ),
            const Gap(12),
            Text('镂空按钮', style: context.h3),
            const Gap(8),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                ElButton2('Default: $count', plain: true, disabled: disabled, onClick: addCount),
                ElButton2('Primary: $count',
                    type: ElThemeType.primary, plain: true, disabled: disabled, onClick: addCount),
                ElButton2('Success: $count',
                    type: ElThemeType.success, plain: true, disabled: disabled, onClick: addCount),
                ElButton2('Info: $count', type: ElThemeType.info, plain: true, disabled: disabled, onClick: addCount),
                ElButton2('Warning: $count',
                    type: ElThemeType.warning, plain: true, disabled: disabled, onClick: addCount),
                ElButton2('Error: $count', type: ElThemeType.error, plain: true, disabled: disabled, onClick: addCount),
              ],
            ),
            const Gap(12),
            Text('圆角按钮', style: context.h3),
            const Gap(8),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                ElButton2('Default: $count', round: true, disabled: disabled, onClick: addCount),
                ElButton2('Primary: $count',
                    type: ElThemeType.primary, round: true, disabled: disabled, onClick: addCount),
                ElButton2('Success: $count',
                    type: ElThemeType.success, round: true, disabled: disabled, onClick: addCount),
                ElButton2('Info: $count', type: ElThemeType.info, round: true, disabled: disabled, onClick: addCount),
                ElButton2('Warning: $count',
                    type: ElThemeType.warning, round: true, disabled: disabled, onClick: addCount),
                ElButton2('Error: $count', type: ElThemeType.error, round: true, disabled: disabled, onClick: addCount),
              ],
            ),
            const Gap(12),
            Text('圆角镂空按钮', style: context.h3),
            const Gap(8),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                ElButton2('Default: $count', round: true, plain: true, disabled: disabled, onClick: addCount),
                ElButton2('Primary: $count',
                    type: ElThemeType.primary, round: true, plain: true, disabled: disabled, onClick: addCount),
                ElButton2('Success: $count',
                    type: ElThemeType.success, round: true, plain: true, disabled: disabled, onClick: addCount),
                ElButton2('Info: $count',
                    type: ElThemeType.info, round: true, plain: true, disabled: disabled, onClick: addCount),
                ElButton2('Warning: $count',
                    type: ElThemeType.warning, round: true, plain: true, disabled: disabled, onClick: addCount),
                ElButton2('Error: $count',
                    type: ElThemeType.error, round: true, plain: true, disabled: disabled, onClick: addCount),
              ],
            ),
            const Gap(12),
            Text('文字按钮', style: context.h3),
            const Gap(8),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                ElButton2('Default: $count', text: true, disabled: disabled, onClick: addCount),
                ElButton2('Primary: $count',
                    type: ElThemeType.primary, text: true, disabled: disabled, onClick: addCount),
                ElButton2('Success: $count',
                    type: ElThemeType.success, text: true, disabled: disabled, onClick: addCount),
                ElButton2('Info: $count', type: ElThemeType.info, text: true, disabled: disabled, onClick: addCount),
                ElButton2('Warning: $count',
                    type: ElThemeType.warning, text: true, disabled: disabled, onClick: addCount),
                ElButton2('Error: $count', type: ElThemeType.error, text: true, disabled: disabled, onClick: addCount),
              ],
            ),
            const Gap(12),
            Text('文字圆角按钮', style: context.h3),
            const Gap(8),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                ElButton2('Default: $count', text: true, round: true, disabled: disabled, onClick: addCount),
                ElButton2('Primary: $count',
                    type: ElThemeType.primary, text: true, round: true, disabled: disabled, onClick: addCount),
                ElButton2('Success: $count',
                    type: ElThemeType.success, text: true, round: true, disabled: disabled, onClick: addCount),
                ElButton2('Info: $count',
                    type: ElThemeType.info, text: true, round: true, disabled: disabled, onClick: addCount),
                ElButton2('Warning: $count',
                    type: ElThemeType.warning, text: true, round: true, disabled: disabled, onClick: addCount),
                ElButton2('Error: $count',
                    type: ElThemeType.error, text: true, round: true, disabled: disabled, onClick: addCount),
              ],
            ),
            const Gap(12),
            Text('图标按钮', style: context.h3),
            const Gap(8),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                ElButton2(null, icon: ElIcon.svg(ElIcons.document), disabled: disabled, onClick: addCount),
                ElButton2('Primary: $count',
                    type: ElThemeType.primary, text: true, disabled: disabled, onClick: addCount),
                ElButton2('Success: $count',
                    type: ElThemeType.success, text: true, disabled: disabled, onClick: addCount),
                ElButton2('Info: $count', type: ElThemeType.info, text: true, disabled: disabled, onClick: addCount),
                ElButton2('Warning: $count',
                    type: ElThemeType.warning, text: true, disabled: disabled, onClick: addCount),
                ElButton2('Error: $count', type: ElThemeType.error, text: true, disabled: disabled, onClick: addCount),
              ],
            ),
            const Gap(12),
            Text('块级按钮', style: context.h3),
            const Gap(8),
            ElButton2('Default: $count', block: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Primary: $count', type: ElThemeType.primary, block: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Success: $count', type: ElThemeType.success, block: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Info: $count', type: ElThemeType.info, block: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Warning: $count', type: ElThemeType.warning, block: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Error: $count', type: ElThemeType.error, block: true, disabled: disabled, onClick: addCount),
            const Gap(12),
            Text('块级镂空按钮', style: context.h3),
            const Gap(8),
            ElButton2('Default: $count', block: true, plain: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Primary: $count',
                type: ElThemeType.primary, block: true, plain: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Success: $count',
                type: ElThemeType.success, block: true, plain: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Info: $count',
                type: ElThemeType.info, block: true, plain: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Warning: $count',
                type: ElThemeType.warning, block: true, plain: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Error: $count',
                type: ElThemeType.error, block: true, plain: true, disabled: disabled, onClick: addCount),
            const Gap(12),
            Text('块级圆角按钮', style: context.h3),
            const Gap(8),
            ElButton2('Default: $count', block: true, round: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Primary: $count',
                type: ElThemeType.primary, block: true, round: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Success: $count',
                type: ElThemeType.success, block: true, round: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Info: $count',
                type: ElThemeType.info, block: true, round: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Warning: $count',
                type: ElThemeType.warning, block: true, round: true, disabled: disabled, onClick: addCount),
            const Gap(8),
            ElButton2('Error: $count',
                type: ElThemeType.error, block: true, round: true, disabled: disabled, onClick: addCount),
          ],
        ),
      ),
    );
  }
}
