name: element_docs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_element_ui:
    path: ../flutter_element_ui
  element_extension:
    path: ../element_extension
  flutter_base:
    git:
      url: https://gitee.com/luoyi666/flutter_base.git
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  syntax_highlight: ^0.4.0
  decimal: ^3.0.0
  boxy: ^2.2.0
  web: ^1.0.0
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  web: ^1.0.0
  flutter_element_ui:
    path: ../flutter_element_ui
  element_extension:
    path: ../element_extension

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/home/
  fonts:
    - family: Consolas
      fonts:
        - asset: assets/fonts/Consolas-Regular.ttf
