name: element_docs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_base:
    path: ../flutter_base
  collection: ^1.18.0
  go_router: ^14.1.4
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  syntax_highlight: ^0.4.0
  decimal: ^3.0.0
  boxy: ^2.2.0
  faker: 2.1.0
  web: ^1.0.0
  url_strategy: ^0.3.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  web: ^1.0.0
#  file_picker:
#    git:
#      url: https://github.com/abdelaziz-mahdy/flutter_file_picker
#      ref: fix-flutter-3.27-compile-error

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/contribute/
    - assets/code_themes/
  fonts:
    - family: Consolas
      fonts:
        - asset: assets/fonts/Consolas-Regular.ttf

