name: element_docs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  element_dart:
    path: ../packages/element_dart
  element_plus:
    path: ../packages/element_plus
  element_extension:
    path: ../packages/element_extension
  element_annotation:
    path: ../packages/element_annotation
  flutter_base:
    git:
      url: https://gitee.com/luoyi666/flutter_base.git
  flutter_obs: ^1.6.3
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  syntax_highlight: ^0.4.0
  decimal: ^3.0.0
  boxy: ^2.2.0
  web: ^1.0.0
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  web: ^1.0.0
  element_plus:
    path: ../packages/element_plus
  element_dart:
    path: ../packages/element_dart
  element_extension:
    path: ../packages/element_extension
  flutter_obs:
    path: ../packages/flutter_obs

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/home/
  fonts:
    - family: Consolas
      fonts:
        - asset: assets/fonts/Consolas-Regular.ttf
