name: element_flutter
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  element_plus:
    path: ../element_plus
  element_dart:
    path: ../element_dart
  element_annotation:
    path: ../element_annotation
  flutter_obs:
    path: ../flutter_obs
  intl: ^0.19.0
  web: ^1.0.0
  http: ^1.2.2
  meta: ^1.12.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.3
  gap: ^3.0.1
  flutter_hooks: ^0.20.5
  super_sliver_list: ^0.4.1

dev_dependencies:
  flutter_lints: ^4.0.0
