targets:
  $default:
    auto_apply_builders: true
    sources:
      - lib/**
      - test/**
      - $package$
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^test/element_generates/models/{{}}.dart': 'test/element_generates/generates/models/{{}}.g.dart'
      element_generator|model:
        generate_for:
          - test/element_generates/models/**.dart
