name: element_test
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  element_plus:
    path: ../packages/element_plus
  element_extension:
    path: ../packages/element_extension
  element_dart:
    path: ../packages/element_dart
  element_annotation:
    path: ../packages/element_annotation
  flutter_obs:
    path: ../packages/flutter_obs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  element_generator:
    path: ../packages/element_generator

dependency_overrides:
  flutter_obs:
    path: ../packages/flutter_obs
