name: flutter_obs
description: "a easy flutter state management"
version: 1.5.4
homepage: https://github.com/luoyi58624/flutter_element_ui/packages/flutter_obs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  element_storage:
    path: ../element_storage
  element_annotation:
    path: ../element_annotation
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_lints: ^4.0.0
