name: flutter_obs
description: "a easy flutter state management"
version: 1.5.4
homepage: https://github.com/luoyi58624/flutter_element_ui/packages/flutter_obs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_serialize:
    path: ../dart_serialize

dev_dependencies:
  flutter_lints: ^4.0.0
