targets:
  $default:
    auto_apply_builders: true
    sources:
      - lib/**
      - $package$
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generates/{{}}.g.dart'
      flutter_element_generator|model:
        generate_for:
          - lib/modals/**.dart