name: docs
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_base:
    git:
      url: https://gitee.com/luoyi666/flutter_base.git
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  syntax_highlight: ^0.4.0
  decimal: ^3.0.0
  flutter_element_ui:
    path: ../
  boxy: ^2.2.0
  web: ^1.0.0
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  web: ^1.0.0
  flutter_element_ui:
    path: ../
  flutter_element_extension:
    path: ../packages/flutter_element_extension
  luoyi_dart_base:
    git:
      url: https://github.com/luoyi58624/luoyi_dart_base.git
  luoyi_flutter_base:
    git:
      url: https://github.com/luoyi58624/luoyi_flutter_base.git

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/home/
  fonts:
    - family: Consolas
      fonts:
        - asset: assets/fonts/Consolas-Regular.ttf
