name: build example web page

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
      - run: sh ./scripts/web_page.sh
      - name: Deploy Web
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: web_page
          folder: element_docs/build/web
          clean: true
