name: my server deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            export PATH="$PATH:~/.pub-cache/bin"
            cd /www/wwwroot/flutter_element_ui
            git fetch --all
            git reset --hard origin/main
            git pull  
            flutter --version
            flutter pub upgrade
            cd example
            flutter pub upgrade
            flutter build web
            sh ./docker_shell.sh
            
